<?php
/**
 * @var string $html       Parsed markdown HTML
 * @var array  $toc        List<{level, text, id}>
 * @var array  $sections   Whitelist sections
 * @var string $currentSlug
 * @var string $pageTitle
 * @var string $icon
 */
use App\Helpers\View;
?>
<style>
    .help-content { line-height: 1.7; }
    .help-content h1 { font-size: 1.9rem; margin-top: 0; }
    .help-content h2 { font-size: 1.5rem; margin-top: 2rem; padding-top: .5rem; border-top: 1px solid #eee; }
    .help-content h3 { font-size: 1.2rem; margin-top: 1.5rem; }
    .help-content h2[id], .help-content h3[id] { scroll-margin-top: 1rem; }
    .help-content pre { background: #f6f8fa; padding: 1rem; border-radius: .375rem; overflow-x: auto; }
    .help-content code { background: #f6f8fa; padding: .15em .3em; border-radius: .25rem; font-size: .9em; }
    .help-content pre code { background: transparent; padding: 0; }
    .help-content blockquote { border-left: 4px solid #ee2c28; padding: .25rem 1rem; color: #555; background: #fff5f5; margin: 1rem 0; }
    .help-content table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    .help-content table th, .help-content table td { border: 1px solid #ddd; padding: .4rem .6rem; }
    .help-toc { position: sticky; top: 1rem; }
    .help-toc a { display: block; padding: .25rem 0; color: #555; text-decoration: none; font-size: .9rem; }
    .help-toc a:hover { color: var(--app-primary, #ee2c28); }
    .help-toc .toc-l3 { padding-left: 1rem; font-size: .85rem; }
    .help-nav-list a { display: block; padding: .3rem .5rem; border-radius: .25rem; color: #444; text-decoration: none; font-size: .9rem; }
    .help-nav-list a.active { background: var(--app-primary, #ee2c28); color: #fff; }
    .help-nav-list a:hover:not(.active) { background: #f5f5f5; }
</style>

<div class="container py-4">
    <nav aria-label="breadcrumb" class="small mb-3">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="<?= url('help') ?>">Pomoc</a></li>
            <li class="breadcrumb-item active" aria-current="page"><?= View::e($pageTitle) ?></li>
        </ol>
    </nav>

    <div class="row g-4">
        <aside class="col-12 col-lg-3 order-2 order-lg-1">
            <div class="help-toc">
                <h6 class="text-uppercase text-muted small mb-2">Sekcje pomocy</h6>
                <div class="help-nav-list mb-4">
                    <?php foreach ($sections as $slug => $sec): ?>
                        <a href="<?= url('help/' . $slug) ?>"
                           class="<?= $slug === $currentSlug ? 'active' : '' ?>">
                            <i class="bi <?= View::e($sec['icon']) ?> me-1"></i>
                            <?= View::e($sec['title']) ?>
                        </a>
                    <?php endforeach; ?>
                </div>

                <?php if (!empty($toc)): ?>
                    <h6 class="text-uppercase text-muted small mb-2">Spis treści</h6>
                    <nav>
                        <?php foreach ($toc as $item): ?>
                            <a href="#<?= View::e($item['id']) ?>" class="toc-l<?= (int)$item['level'] ?>">
                                <?= View::e($item['text']) ?>
                            </a>
                        <?php endforeach; ?>
                    </nav>
                <?php endif; ?>
            </div>
        </aside>

        <article class="col-12 col-lg-9 order-1 order-lg-2">
            <div class="d-flex align-items-center gap-2 mb-3">
                <i class="bi <?= View::e($icon ?? 'bi-book') ?> fs-2 text-primary"></i>
                <h1 class="mb-0"><?= View::e($pageTitle) ?></h1>
            </div>
            <div class="help-content">
                <?= $html /* generated by Markdown::render — input escape'owany w parserze */ ?>
            </div>
            <hr class="mt-5">
            <p class="small text-muted">
                Renderowane przez wbudowany markdown parser ClubDesk.
                <span class="ms-2"><a href="<?= url('help') ?>"><i class="bi bi-arrow-left"></i> Powrót do centrum pomocy</a></span>
            </p>
        </article>
    </div>
</div>
