<?php
return [
    'key'        => 'equestrian',
    'name'       => 'Jeździectwo',
    'federation' => 'PZJ',
    'archetype'  => \App\Sports\Equestrian\EquestrianArchetype::class,
    'features'   => ['horses', 'owners', 'riders', 'pzj_license', 'competitions', 'results', 'disciplines', 'dressage', 'jumping', 'pzj_passport', 'fei_passport', 'fei_horses', 'fei_ranking', 'eventing', 'demo-ready'],
    'routes' => [
        ['GET',  '/equestrian/horses',                    [\App\Sports\Equestrian\Controllers\HorsesController::class,  'index']],
        ['POST', '/equestrian/horses/store',               [\App\Sports\Equestrian\Controllers\HorsesController::class,  'store']],
        ['POST', '/equestrian/horses/:id/delete',          [\App\Sports\Equestrian\Controllers\HorsesController::class,  'delete']],
        ['GET',  '/equestrian/owners',                     [\App\Sports\Equestrian\Controllers\OwnersController::class, 'index']],
        ['POST', '/equestrian/owners/store',               [\App\Sports\Equestrian\Controllers\OwnersController::class, 'store']],
        ['POST', '/equestrian/owners/:id/delete',          [\App\Sports\Equestrian\Controllers\OwnersController::class, 'delete']],
        ['GET',  '/equestrian/riders',                     [\App\Sports\Equestrian\Controllers\RidersController::class, 'index']],
        ['POST', '/equestrian/riders/store',               [\App\Sports\Equestrian\Controllers\RidersController::class, 'store']],
        ['POST', '/equestrian/riders/:id/delete',          [\App\Sports\Equestrian\Controllers\RidersController::class, 'delete']],
        ['GET',  '/equestrian/competitions',               [\App\Sports\Equestrian\Controllers\CompetitionsController::class, 'index']],
        ['POST', '/equestrian/competitions/store',         [\App\Sports\Equestrian\Controllers\CompetitionsController::class, 'store']],
        ['GET',  '/equestrian/competitions/:id',           [\App\Sports\Equestrian\Controllers\CompetitionsController::class, 'show']],
        ['POST', '/equestrian/competitions/:id/delete',    [\App\Sports\Equestrian\Controllers\CompetitionsController::class, 'delete']],
        ['POST', '/equestrian/competitions/:id/class',     [\App\Sports\Equestrian\Controllers\CompetitionsController::class, 'addClass']],
        ['POST', '/equestrian/classes/:id/delete',         [\App\Sports\Equestrian\Controllers\CompetitionsController::class, 'deleteClass']],
        ['GET',  '/equestrian/results',                    [\App\Sports\Equestrian\Controllers\ResultsController::class, 'index']],
        ['POST', '/equestrian/results/store',              [\App\Sports\Equestrian\Controllers\ResultsController::class, 'store']],
        ['POST', '/equestrian/results/:id/delete',         [\App\Sports\Equestrian\Controllers\ResultsController::class, 'delete']],
        // FULL: FEI horses registry + FEI results (dressage/jumping/eventing/...)
        ['GET',  '/equestrian/fei-horses',                 [\App\Sports\Equestrian\Controllers\FeiHorsesController::class, 'index']],
        ['POST', '/equestrian/fei-horses/store',           [\App\Sports\Equestrian\Controllers\FeiHorsesController::class, 'store']],
        ['POST', '/equestrian/fei-horses/:id/delete',      [\App\Sports\Equestrian\Controllers\FeiHorsesController::class, 'delete']],
        ['GET',  '/equestrian/fei-results',                [\App\Sports\Equestrian\Controllers\FeiResultsController::class, 'index']],
        ['POST', '/equestrian/fei-results/store',          [\App\Sports\Equestrian\Controllers\FeiResultsController::class, 'store']],
        ['POST', '/equestrian/fei-results/:id/delete',     [\App\Sports\Equestrian\Controllers\FeiResultsController::class, 'delete']],
    ],
    'nav' => [
        ['label' => 'Konie',           'icon' => 'bi-compass',         'url' => 'equestrian/horses'],
        ['label' => 'Właściciele',     'icon' => 'bi-person-vcard',    'url' => 'equestrian/owners'],
        ['label' => 'Zawodnicy PZJ',   'icon' => 'bi-person-badge',    'url' => 'equestrian/riders'],
        ['label' => 'Zawody',          'icon' => 'bi-flag',            'url' => 'equestrian/competitions'],
        ['label' => 'Wyniki',          'icon' => 'bi-trophy',          'url' => 'equestrian/results'],
        ['label' => 'Rejestr FEI',     'icon' => 'bi-card-list',       'url' => 'equestrian/fei-horses'],
        ['label' => 'Wyniki FEI',      'icon' => 'bi-bar-chart-line',  'url' => 'equestrian/fei-results'],
    ],
    'views_path' => __DIR__ . '/views',
    'migrations' => __DIR__ . '/migrations',
];
