<?php

declare(strict_types=1);

namespace App\Helpers\Tournaments;

use App\Helpers\Database;
use App\Helpers\Pdf\TournamentProtocolPdf;
use App\Helpers\PdfHelper;
use App\Models\SportModel;
use App\Models\TournamentProtocolModel;
use PDO;
use RuntimeException;
use Throwable;

/**
 * Publikuje i wersjonuje PDF protokol turnieju, opcjonalnie wystawiajac
 * publiczny share link (`public_share_slug`).
 *
 * Lifecycle:
 *   - publish()     — pierwsza wersja (v1) lub no-op gdy juz jest wpis.
 *   - republish()   — bumpuje version + 1, slug zachowany.
 *
 * Best-effort: failure NIGDY nie powinien blokowac glownej operacji
 * (zmiana statusu turnieju). Wywolujacy decyduje, czy lapac wyjatek.
 *
 * Storage layout:
 *   ROOT_PATH/storage/tournament_protocols/{club_id}/{tournament_id}_v{N}.pdf
 *   (POZA /public/ — dostep tylko przez kontroler download)
 */
class ProtocolPublisher
{
    private TournamentProtocolModel $model;
    private PDO $db;

    public function __construct(?TournamentProtocolModel $model = null, ?PDO $db = null)
    {
        $this->db    = $db ?? Database::pdo();
        $this->model = $model ?? new TournamentProtocolModel($this->db);
    }

    /**
     * Publikuj pierwsza wersje protokolu. Idempotent: jesli juz istnieje
     * wpis dla turnieju, zwraca metadane istniejacej najnowszej wersji
     * bez regeneracji PDF (chyba ze ktos chce republish — patrz republish()).
     *
     * @return array{path:string, share_url:?string, version:int, share_enabled:bool}
     */
    public function publish(int $tournamentId): array
    {
        $existing = $this->model->latestForTournament($tournamentId);
        if ($existing !== null) {
            return $this->meta($existing);
        }
        return $this->writeVersion($tournamentId, version: 1, autoGenerated: true);
    }

    /**
     * Re-publikuj protokol — bumpuje version + 1 i zachowuje istniejacy slug
     * (jesli byl wlaczony share link, nadal dziala).
     *
     * @return array{path:string, share_url:?string, version:int, share_enabled:bool}
     */
    public function republish(int $tournamentId): array
    {
        $existing = $this->model->latestForTournament($tournamentId);
        $nextVersion = $existing !== null ? ((int)$existing['version']) + 1 : 1;

        $keepSlug    = $existing['public_share_slug']    ?? null;
        $keepEnabled = (int)($existing['public_share_enabled'] ?? 0) === 1;

        return $this->writeVersion(
            $tournamentId,
            version: $nextVersion,
            autoGenerated: false,
            inheritSlug: $keepSlug,
            inheritShareEnabled: $keepEnabled,
        );
    }

    /**
     * Wymus wlaczenie / wylaczenie publicznego share-linka. Przy pierwszym
     * wlaczeniu generuje slug. Zwraca pelny URL lub null gdy disabled.
     */
    public function setSharing(int $tournamentId, bool $enabled): ?string
    {
        $latest = $this->model->latestForTournament($tournamentId);
        if ($latest === null) {
            // Nie ma jeszcze protokolu — wygeneruj v1.
            $latest = ['id' => 0, 'version' => 0, 'public_share_slug' => null];
            $meta = $this->publish($tournamentId);
            $slug = $this->generateUniqueSlug($tournamentId);
        } else {
            $slug = $latest['public_share_slug'] ?? null;
        }

        if ($enabled && empty($slug)) {
            $slug = $this->generateUniqueSlug($tournamentId);
        }

        $this->model->setShareEnabled($tournamentId, $enabled, $slug);
        return ($enabled && $slug !== null) ? $this->buildShareUrl($slug) : null;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Internals
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Wygeneruj PDF + zapisz wersje do DB. Wspolny core dla publish/republish.
     *
     * @return array{path:string, share_url:?string, version:int, share_enabled:bool}
     */
    private function writeVersion(
        int $tournamentId,
        int $version,
        bool $autoGenerated,
        ?string $inheritSlug = null,
        bool $inheritShareEnabled = false,
    ): array {
        $tournament = $this->loadTournament($tournamentId);
        if ($tournament === null) {
            throw new RuntimeException("Tournament {$tournamentId} not found");
        }
        $clubId = (int)$tournament['club_id'];

        $participants = $this->loadParticipants($tournamentId);
        $matches      = $this->loadMatches($tournamentId);
        $sport        = (new SportModel())->findByKey((string)$tournament['sport_key']) ?? [];

        $html = TournamentProtocolPdf::generate([
            'tournament'    => $tournament,
            'participants'  => $participants,
            'matches'       => $matches,
            'sport'         => $sport,
            'club_header'   => PdfHelper::getClubHeader($clubId),
            'system_footer' => PdfHelper::getSystemFooter(),
        ]);

        $pdfBytes  = $this->renderPdfToString($html, "protokol-turnieju-{$tournamentId}.pdf");
        $relPath   = $this->buildRelPath($clubId, $tournamentId, $version);
        $this->writeFile($relPath, $pdfBytes);

        $this->model->insertVersion([
            'tournament_id'        => $tournamentId,
            'club_id'              => $clubId,
            'version'              => $version,
            'pdf_path'             => $relPath,
            'pdf_size_bytes'       => strlen($pdfBytes),
            'pdf_hash'             => hash('sha256', $pdfBytes),
            'public_share_slug'    => $inheritSlug,
            'public_share_enabled' => $inheritShareEnabled ? 1 : 0,
            'auto_generated'       => $autoGenerated ? 1 : 0,
        ]);

        return [
            'path'          => $relPath,
            'share_url'     => ($inheritShareEnabled && $inheritSlug)
                ? $this->buildShareUrl($inheritSlug)
                : null,
            'version'       => $version,
            'share_enabled' => $inheritShareEnabled,
        ];
    }

    private function meta(array $row): array
    {
        $slug    = $row['public_share_slug'] ?? null;
        $enabled = (int)($row['public_share_enabled'] ?? 0) === 1;
        return [
            'path'          => (string)$row['pdf_path'],
            'share_url'     => ($enabled && $slug) ? $this->buildShareUrl($slug) : null,
            'version'       => (int)$row['version'],
            'share_enabled' => $enabled,
        ];
    }

    private function loadTournament(int $id): ?array
    {
        $stmt = $this->db->prepare("SELECT * FROM tournaments WHERE id = ? LIMIT 1");
        $stmt->execute([$id]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        return $row ?: null;
    }

    private function loadParticipants(int $tournamentId): array
    {
        $stmt = $this->db->prepare(
            "SELECT tp.*, m.first_name, m.last_name, m.member_number
               FROM tournament_participants tp
               JOIN members m ON m.id = tp.member_id
              WHERE tp.tournament_id = ?
           ORDER BY tp.seed ASC, m.last_name ASC"
        );
        $stmt->execute([$tournamentId]);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    private function loadMatches(int $tournamentId): array
    {
        $stmt = $this->db->prepare(
            "SELECT tm.*,
                    CONCAT(m1.last_name, ' ', m1.first_name) AS player1_name,
                    CONCAT(m2.last_name, ' ', m2.first_name) AS player2_name
               FROM tournament_matches tm
          LEFT JOIN members m1 ON m1.id = tm.player1_id
          LEFT JOIN members m2 ON m2.id = tm.player2_id
              WHERE tm.tournament_id = ?
           ORDER BY tm.round ASC, tm.match_number ASC"
        );
        $stmt->execute([$tournamentId]);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    /**
     * Render HTML do PDF zwracajac bajty (NIE wysylajac do przegladarki).
     * Fallback gdy mPDF brak: zwraca HTML jako bajty (tymczasowe — admin
     * UI poinformuje o braku mpdf).
     */
    private function renderPdfToString(string $html, string $filename): string
    {
        if (class_exists(\Mpdf\Mpdf::class)) {
            $tempDir = ROOT_PATH . '/storage/tmp';
            if (!is_dir($tempDir)) {
                @mkdir($tempDir, 0775, true);
            }
            if (!is_writable($tempDir)) {
                $tempDir = sys_get_temp_dir() . '/mpdf_' . md5(ROOT_PATH);
                if (!is_dir($tempDir)) {
                    @mkdir($tempDir, 0775, true);
                }
            }

            $mpdf = new \Mpdf\Mpdf([
                'mode'          => 'utf-8',
                'format'        => 'A4',
                'orientation'   => 'P',
                'margin_left'   => 15,
                'margin_right'  => 15,
                'margin_top'    => 16,
                'margin_bottom' => 16,
                'margin_header' => 9,
                'margin_footer' => 9,
                'tempDir'       => $tempDir,
            ]);
            $mpdf->SetTitle($filename);
            $mpdf->WriteHTML($html);
            // Destination::STRING_RETURN = 'S' — zwraca jako string bajtow.
            return (string)$mpdf->Output('', \Mpdf\Output\Destination::STRING_RETURN);
        }

        // Fallback: zwroc HTML jako "PDF" (przegladarka wyrenderuje).
        // Admin UI bedzie widzial size_bytes > 0, ale plik nie bedzie PDF.
        return $html;
    }

    private function buildRelPath(int $clubId, int $tournamentId, int $version): string
    {
        return sprintf(
            'storage/tournament_protocols/%d/%d_v%d.pdf',
            $clubId,
            $tournamentId,
            $version,
        );
    }

    private function writeFile(string $relPath, string $bytes): void
    {
        $absPath = ROOT_PATH . '/' . $relPath;
        $dir     = dirname($absPath);
        if (!is_dir($dir)) {
            if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
                throw new RuntimeException("Cannot create dir: {$dir}");
            }
        }
        $ok = @file_put_contents($absPath, $bytes);
        if ($ok === false) {
            throw new RuntimeException("Cannot write PDF: {$absPath}");
        }
        // Best-effort permissions.
        @chmod($absPath, 0640);
    }

    /**
     * Generuj globalnie unikalny slug (cross-tenant) dla tournament_protocols.
     * Wzorzec ten sam co TournamentModel::generatePublicLiveSlug
     * (slugify(name) + '-' + 6 hex), z retry przy kolizji.
     */
    private function generateUniqueSlug(int $tournamentId): string
    {
        $stmt = $this->db->prepare("SELECT name FROM tournaments WHERE id = ? LIMIT 1");
        $stmt->execute([$tournamentId]);
        $name = (string)($stmt->fetchColumn() ?: 'turniej');

        $base = \App\Models\TournamentModel::slugify($name);
        if ($base === '') {
            $base = 'turniej';
        }
        if (strlen($base) > 73) {
            $base = rtrim(substr($base, 0, 73), '-');
        }

        for ($attempt = 0; $attempt < 8; $attempt++) {
            try {
                $suffix = strtolower(bin2hex(random_bytes(3))); // 6 hex
            } catch (Throwable) {
                $suffix = substr(md5((string)microtime(true) . $attempt), 0, 6);
            }
            $candidate = $base . '-' . $suffix;
            if (!$this->model->slugExists($candidate)) {
                return $candidate;
            }
        }
        throw new RuntimeException('Could not generate unique tournament_protocols.public_share_slug');
    }

    private function buildShareUrl(string $slug): string
    {
        if (function_exists('url')) {
            return url('protocols/' . $slug);
        }
        // Fallback gdy helper niezaladowany (CLI bez Helpers.php).
        $base = defined('BASE_URL') ? BASE_URL : '';
        return rtrim($base, '/') . '/protocols/' . $slug;
    }
}
