<?php
// Football plugin manifest
return [
    'key'        => 'football',
    'name'       => 'Piłka nożna',
    'federation' => 'PZPN',
    'archetype'  => \App\Sports\Football\FootballArchetype::class,
    'features'   => ['teams','positions','matches','cards','transfers','stats','leagues','pzpn_license','demo-ready'],
    'routes' => [
        ['GET',  '/football/teams',              [\App\Sports\Football\Controllers\TeamsController::class, 'index']],
        ['GET',  '/football/teams/create',       [\App\Sports\Football\Controllers\TeamsController::class, 'create']],
        ['POST', '/football/teams/store',        [\App\Sports\Football\Controllers\TeamsController::class, 'store']],
        ['GET',  '/football/teams/:id/edit',     [\App\Sports\Football\Controllers\TeamsController::class, 'edit']],
        ['POST', '/football/teams/:id/update',   [\App\Sports\Football\Controllers\TeamsController::class, 'update']],
        ['POST', '/football/teams/:id/delete',   [\App\Sports\Football\Controllers\TeamsController::class, 'delete']],
        ['GET',  '/football/matches',            [\App\Sports\Football\Controllers\MatchesController::class, 'index']],
        ['GET',  '/football/matches/create',     [\App\Sports\Football\Controllers\MatchesController::class, 'create']],
        ['POST', '/football/matches/store',      [\App\Sports\Football\Controllers\MatchesController::class, 'store']],
        ['GET',  '/football/matches/:id',        [\App\Sports\Football\Controllers\MatchesController::class, 'show']],
        ['GET',  '/football/matches/:id/edit',   [\App\Sports\Football\Controllers\MatchesController::class, 'edit']],
        ['POST', '/football/matches/:id/update', [\App\Sports\Football\Controllers\MatchesController::class, 'update']],
        ['POST', '/football/matches/:id/delete', [\App\Sports\Football\Controllers\MatchesController::class, 'delete']],
        ['POST', '/football/matches/:id/event',  [\App\Sports\Football\Controllers\MatchesController::class, 'addEvent']],
        ['POST', '/football/matches/:id/lineup', [\App\Sports\Football\Controllers\MatchesController::class, 'addLineup']],
        ['POST', '/football/matches/:id/lineup-save', [\App\Sports\Football\Controllers\MatchesController::class, 'saveLineup']],
        ['GET',  '/football/transfers',           [\App\Sports\Football\Controllers\TransfersController::class, 'index']],
        ['GET',  '/football/transfers/create',    [\App\Sports\Football\Controllers\TransfersController::class, 'create']],
        ['POST', '/football/transfers/store',     [\App\Sports\Football\Controllers\TransfersController::class, 'store']],
        ['POST', '/football/transfers/:id/delete',[\App\Sports\Football\Controllers\TransfersController::class, 'delete']],
        ['GET',  '/football/leagues',              [\App\Sports\Football\Controllers\LeaguesController::class, 'index']],
        ['GET',  '/football/leagues/create',       [\App\Sports\Football\Controllers\LeaguesController::class, 'create']],
        ['POST', '/football/leagues/store',        [\App\Sports\Football\Controllers\LeaguesController::class, 'store']],
        ['GET',  '/football/leagues/:id',          [\App\Sports\Football\Controllers\LeaguesController::class, 'show']],
        ['POST', '/football/leagues/:id/delete',   [\App\Sports\Football\Controllers\LeaguesController::class, 'delete']],
        ['GET',  '/football/stats',                [\App\Sports\Football\Controllers\StatsController::class, 'index']],
    ],
    'nav' => [
        ['label' => 'Drużyny',    'icon' => 'bi-people',           'url' => 'football/teams'],
        ['label' => 'Mecze',      'icon' => 'bi-flag',             'url' => 'football/matches'],
        ['label' => 'Transfery',  'icon' => 'bi-arrow-left-right', 'url' => 'football/transfers'],
        ['label' => 'Ligi',       'icon' => 'bi-table',            'url' => 'football/leagues'],
        ['label' => 'Statystyki', 'icon' => 'bi-bar-chart',        'url' => 'football/stats'],
    ],
    'views_path' => __DIR__ . '/views',
    'migrations' => __DIR__ . '/migrations',
];
