-- 069: Katalog dostepnych eventow ktore moga wyzwalac email per klub.
-- Pozwala administratorom zobaczyc liste wszystkich dostepnych
-- "zdarzen" (welcome, fee_reminder, training_cancelled, ...) z opisem,
-- domyslnym subject/body i lista dostepnych placeholderow.

SET foreign_key_checks = 0;

CREATE TABLE IF NOT EXISTS `email_event_catalog` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `code` VARCHAR(60) NOT NULL UNIQUE,
    `name` VARCHAR(120) NOT NULL,
    `description` VARCHAR(500) NULL,
    `category` VARCHAR(40) NOT NULL DEFAULT 'general',
    `default_subject` VARCHAR(200) NULL,
    `default_body` TEXT NULL,
    `available_variables` JSON NULL COMMENT 'Lista placeholderow, np. ["member.first_name","fee.amount"]',
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `sort_order` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    KEY `idx_eec_category` (`category`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Katalog eventow ktore moga wyzwalac email';

-- Seed eventow
INSERT IGNORE INTO `email_event_catalog`
    (`code`, `name`, `description`, `category`, `default_subject`, `default_body`, `available_variables`, `sort_order`)
VALUES
('member_welcome', 'Powitanie nowego czlonka',
 'Wysylany po dodaniu nowego czlonka do klubu',
 'onboarding',
 'Witaj w klubie {{club.name}}!',
 'Czesc {{member.first_name}},\n\nWitaj w klubie {{club.name}}! Twoj numer czlonkowski to {{member.member_number}}.\n\nPozdrawiamy,\nZarzad klubu {{club.name}}',
 '["member.first_name","member.last_name","member.member_number","club.name","club.email"]',
 10),
('member_password_reset', 'Reset hasla',
 'Link do resetowania hasla czlonka',
 'auth',
 'Reset hasla - {{club.name}}',
 'Czesc {{member.first_name}},\n\nKliknij link aby zresetowac haslo: {{reset_link}}',
 '["member.first_name","reset_link","club.name"]',
 20),
('fee_reminder', 'Przypomnienie o skladce',
 'Przypomnienie o zblizajacym sie terminie skladki',
 'fees',
 'Termin skladki: {{fee.due_date}}',
 'Czesc {{member.first_name}},\n\nPrzypominamy o nadchodzacej skladce {{fee.amount}} PLN, termin: {{fee.due_date}}.',
 '["member.first_name","fee.amount","fee.due_date","payment_link","club.name"]',
 30),
('fee_overdue', 'Zalegla skladka',
 'Skladka po terminie',
 'fees',
 'Zalegla skladka - {{member.first_name}}',
 'Czesc {{member.first_name}},\n\nMasz zaległa skladke {{fee.amount}} PLN (po terminie o {{fee.days_overdue}} dni).',
 '["member.first_name","fee.amount","fee.days_overdue","club.name"]',
 40),
('fee_paid', 'Potwierdzenie wplaty',
 'Potwierdzenie zaksiegowania skladki',
 'fees',
 'Potwierdzenie wplaty - {{fee.amount}} PLN',
 'Czesc {{member.first_name}},\n\nDziekujemy za wplate {{fee.amount}} PLN ({{fee.title}}) z dnia {{fee.paid_date}}.',
 '["member.first_name","fee.amount","fee.paid_date","fee.title","club.name"]',
 50),
('event_invitation', 'Zaproszenie na wydarzenie',
 'Zaproszenie czlonka na wydarzenie/turniej',
 'events',
 'Zaproszenie: {{event.title}}',
 'Czesc {{member.first_name}},\n\nZapraszamy na {{event.title}} dnia {{event.date}} ({{event.location}}).',
 '["member.first_name","event.title","event.date","event.location","club.name"]',
 60),
('event_reminder', 'Przypomnienie o wydarzeniu',
 'Wysylany 24h przed wydarzeniem',
 'events',
 'Jutro: {{event.title}}',
 'Czesc {{member.first_name}},\n\nPrzypominamy: jutro {{event.title}} ({{event.date}}, {{event.location}}).',
 '["member.first_name","event.title","event.date","event.location","club.name"]',
 70),
('training_scheduled', 'Nowy trening',
 'Powiadomienie o nowym treningu w grupie czlonka',
 'trainings',
 'Nowy trening: {{training.date}}',
 'Czesc {{member.first_name}},\n\nZaplanowano nowy trening {{training.title}} dnia {{training.date}} ({{training.location}}).',
 '["member.first_name","training.title","training.date","training.location","club.name"]',
 80),
('training_cancelled', 'Trening odwolany',
 'Anulowanie treningu',
 'trainings',
 'Trening odwolany: {{training.date}}',
 'Czesc {{member.first_name}},\n\nTrening {{training.title}} ({{training.date}}) zostal odwolany. Powod: {{reason}}.',
 '["member.first_name","training.title","training.date","reason","club.name"]',
 90),
('medical_exam_expiring', 'Badania koncza waznosc',
 'Przypomnienie o wygasajacych badaniach okresowych',
 'medical',
 'Badania okresowe wygasaja {{exam.expiry_date}}',
 'Czesc {{member.first_name}},\n\nTwoje badania okresowe wygasna {{exam.expiry_date}} (pozostalo {{exam.days_left}} dni).',
 '["member.first_name","exam.expiry_date","exam.days_left","club.name"]',
 100),
('license_renewal', 'Odnowienie licencji',
 'Termin odnowienia licencji federacyjnej',
 'compliance',
 'Licencja {{license.federation}} - odnowienie',
 'Czesc {{member.first_name}},\n\nTwoja licencja {{license.federation}} wygasa {{license.expiry_date}}. Pamietaj o odnowieniu.',
 '["member.first_name","license.federation","license.expiry_date","club.name"]',
 110);

SET foreign_key_checks = 1;
