ALTER TABLE rowing_results
    ADD COLUMN IF NOT EXISTS time_ms       INT UNSIGNED DEFAULT NULL AFTER age_category,
    ADD COLUMN IF NOT EXISTS distance_m    SMALLINT UNSIGNED DEFAULT NULL AFTER time_ms,
    ADD COLUMN IF NOT EXISTS boat_type     VARCHAR(10) DEFAULT NULL AFTER distance_m;
