<?php
return [
    'key'        => 'athletics',
    'name'       => 'Lekka atletyka',
    'federation' => 'PZLA',
    'archetype'  => \App\Sports\Athletics\AthleticsArchetype::class,
    'features'   => ['disciplines','records','competitions','results','times','pzla_license','demo-ready'],
    'routes' => [
        ['GET',  '/athletics/records',             [\App\Sports\Athletics\Controllers\RecordsController::class, 'index']],
        ['GET',  '/athletics/records/create',      [\App\Sports\Athletics\Controllers\RecordsController::class, 'create']],
        ['POST', '/athletics/records/store',       [\App\Sports\Athletics\Controllers\RecordsController::class, 'store']],
        ['POST', '/athletics/records/:id/delete',  [\App\Sports\Athletics\Controllers\RecordsController::class, 'delete']],
        ['GET',  '/athletics/results',             [\App\Sports\Athletics\Controllers\ResultsController::class, 'index']],
        ['POST', '/athletics/results/store',       [\App\Sports\Athletics\Controllers\ResultsController::class, 'store']],
        ['POST', '/athletics/results/:id/delete',  [\App\Sports\Athletics\Controllers\ResultsController::class, 'delete']],
        ['GET',  '/athletics/competitions',             [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'index']],
        ['GET',  '/athletics/competitions/create',      [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'create']],
        ['POST', '/athletics/competitions/store',       [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'store']],
        ['GET',  '/athletics/competitions/:id',         [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'show']],
        ['GET',  '/athletics/competitions/:id/edit',    [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'edit']],
        ['POST', '/athletics/competitions/:id/update',  [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'update']],
        ['POST', '/athletics/competitions/:id/delete',  [\App\Sports\Athletics\Controllers\CompetitionsController::class, 'delete']],
    ],
    'nav' => [
        ['label' => 'Rekordy',        'icon' => 'bi-trophy', 'url' => 'athletics/records'],
        ['label' => 'Wyniki zawodów', 'icon' => 'bi-flag',   'url' => 'athletics/results'],
        ['label' => 'Zawody',         'icon' => 'bi-calendar-event', 'url' => 'athletics/competitions'],
    ],
    'migrations' => __DIR__ . '/migrations',
];
